// Code generated by MockGen. DO NOT EDIT.
// Source: spotify_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockSpotifyAPI is a mock of SpotifyAPI interface.
type MockSpotifyAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyAPIMockRecorder
}

// MockSpotifyAPIMockRecorder is the mock recorder for MockSpotifyAPI.
type MockSpotifyAPIMockRecorder struct {
	mock *MockSpotifyAPI
}

// NewMockSpotifyAPI creates a new mock instance.
func NewMockSpotifyAPI(ctrl *gomock.Controller) *MockSpotifyAPI {
	mock := &MockSpotifyAPI{ctrl: ctrl}
	mock.recorder = &MockSpotifyAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyAPI) EXPECT() *MockSpotifyAPIMockRecorder {
	return m.recorder
}

// ExchangeCodeForTokens mocks base method.
func (m *MockSpotifyAPI) ExchangeCodeForTokens(ctx context.Context, code string) (*models.SpotifyTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCodeForTokens", ctx, code)
	ret0, _ := ret[0].(*models.SpotifyTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCodeForTokens indicates an expected call of ExchangeCodeForTokens.
func (mr *MockSpotifyAPIMockRecorder) ExchangeCodeForTokens(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCodeForTokens", reflect.TypeOf((*MockSpotifyAPI)(nil).ExchangeCodeForTokens), ctx, code)
}

// GenerateAuthURL mocks base method.
func (m *MockSpotifyAPI) GenerateAuthURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateAuthURL indicates an expected call of GenerateAuthURL.
func (mr *MockSpotifyAPIMockRecorder) GenerateAuthURL(state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthURL", reflect.TypeOf((*MockSpotifyAPI)(nil).GenerateAuthURL), state)
}

// GetUserProfile mocks base method.
func (m *MockSpotifyAPI) GetUserProfile(ctx context.Context, accessToken string) (*models.SpotifyUserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx, accessToken)
	ret0, _ := ret[0].(*models.SpotifyUserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockSpotifyAPIMockRecorder) GetUserProfile(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockSpotifyAPI)(nil).GetUserProfile), ctx, accessToken)
}
