// Code generated by MockGen. DO NOT EDIT.
// Source: spotify_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	spotifyclient "github.com/ngomez18/playlist-router/internal/clients/spotify"
)

// MockSpotifyAPI is a mock of SpotifyAPI interface.
type MockSpotifyAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyAPIMockRecorder
}

// MockSpotifyAPIMockRecorder is the mock recorder for MockSpotifyAPI.
type MockSpotifyAPIMockRecorder struct {
	mock *MockSpotifyAPI
}

// NewMockSpotifyAPI creates a new mock instance.
func NewMockSpotifyAPI(ctrl *gomock.Controller) *MockSpotifyAPI {
	mock := &MockSpotifyAPI{ctrl: ctrl}
	mock.recorder = &MockSpotifyAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyAPI) EXPECT() *MockSpotifyAPIMockRecorder {
	return m.recorder
}

// CreatePlaylist mocks base method.
func (m *MockSpotifyAPI) CreatePlaylist(ctx context.Context, accessToken, userId, name, description string, public bool) (*spotifyclient.SpotifyPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlaylist", ctx, accessToken, userId, name, description, public)
	ret0, _ := ret[0].(*spotifyclient.SpotifyPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlaylist indicates an expected call of CreatePlaylist.
func (mr *MockSpotifyAPIMockRecorder) CreatePlaylist(ctx, accessToken, userId, name, description, public interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlaylist", reflect.TypeOf((*MockSpotifyAPI)(nil).CreatePlaylist), ctx, accessToken, userId, name, description, public)
}

// ExchangeCodeForTokens mocks base method.
func (m *MockSpotifyAPI) ExchangeCodeForTokens(ctx context.Context, code string) (*spotifyclient.SpotifyTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCodeForTokens", ctx, code)
	ret0, _ := ret[0].(*spotifyclient.SpotifyTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCodeForTokens indicates an expected call of ExchangeCodeForTokens.
func (mr *MockSpotifyAPIMockRecorder) ExchangeCodeForTokens(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCodeForTokens", reflect.TypeOf((*MockSpotifyAPI)(nil).ExchangeCodeForTokens), ctx, code)
}

// GenerateAuthURL mocks base method.
func (m *MockSpotifyAPI) GenerateAuthURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateAuthURL indicates an expected call of GenerateAuthURL.
func (mr *MockSpotifyAPIMockRecorder) GenerateAuthURL(state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthURL", reflect.TypeOf((*MockSpotifyAPI)(nil).GenerateAuthURL), state)
}

// GetPlaylist mocks base method.
func (m *MockSpotifyAPI) GetPlaylist(ctx context.Context, accessToken, playlistId string) (*spotifyclient.SpotifyPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaylist", ctx, accessToken, playlistId)
	ret0, _ := ret[0].(*spotifyclient.SpotifyPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaylist indicates an expected call of GetPlaylist.
func (mr *MockSpotifyAPIMockRecorder) GetPlaylist(ctx, accessToken, playlistId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaylist", reflect.TypeOf((*MockSpotifyAPI)(nil).GetPlaylist), ctx, accessToken, playlistId)
}

// GetUserPlaylists mocks base method.
func (m *MockSpotifyAPI) GetUserPlaylists(ctx context.Context, accessToken string, limit, offset int) (*spotifyclient.SpotifyPlaylistResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPlaylists", ctx, accessToken, limit, offset)
	ret0, _ := ret[0].(*spotifyclient.SpotifyPlaylistResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPlaylists indicates an expected call of GetUserPlaylists.
func (mr *MockSpotifyAPIMockRecorder) GetUserPlaylists(ctx, accessToken, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPlaylists", reflect.TypeOf((*MockSpotifyAPI)(nil).GetUserPlaylists), ctx, accessToken, limit, offset)
}

// GetUserProfile mocks base method.
func (m *MockSpotifyAPI) GetUserProfile(ctx context.Context, accessToken string) (*spotifyclient.SpotifyUserProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx, accessToken)
	ret0, _ := ret[0].(*spotifyclient.SpotifyUserProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockSpotifyAPIMockRecorder) GetUserProfile(ctx, accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockSpotifyAPI)(nil).GetUserProfile), ctx, accessToken)
}
