// Code generated by MockGen. DO NOT EDIT.
// Source: base_playlist_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockBasePlaylistRepository is a mock of BasePlaylistRepository interface.
type MockBasePlaylistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBasePlaylistRepositoryMockRecorder
}

// MockBasePlaylistRepositoryMockRecorder is the mock recorder for MockBasePlaylistRepository.
type MockBasePlaylistRepositoryMockRecorder struct {
	mock *MockBasePlaylistRepository
}

// NewMockBasePlaylistRepository creates a new mock instance.
func NewMockBasePlaylistRepository(ctrl *gomock.Controller) *MockBasePlaylistRepository {
	mock := &MockBasePlaylistRepository{ctrl: ctrl}
	mock.recorder = &MockBasePlaylistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasePlaylistRepository) EXPECT() *MockBasePlaylistRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBasePlaylistRepository) Create(ctx context.Context, userId, name, spotifyPlaylistId string) (*models.BasePlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userId, name, spotifyPlaylistId)
	ret0, _ := ret[0].(*models.BasePlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBasePlaylistRepositoryMockRecorder) Create(ctx, userId, name, spotifyPlaylistId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBasePlaylistRepository)(nil).Create), ctx, userId, name, spotifyPlaylistId)
}

// Delete mocks base method.
func (m *MockBasePlaylistRepository) Delete(ctx context.Context, id, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBasePlaylistRepositoryMockRecorder) Delete(ctx, id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBasePlaylistRepository)(nil).Delete), ctx, id, userId)
}

// GetByID mocks base method.
func (m *MockBasePlaylistRepository) GetByID(ctx context.Context, id, userId string) (*models.BasePlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userId)
	ret0, _ := ret[0].(*models.BasePlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBasePlaylistRepositoryMockRecorder) GetByID(ctx, id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBasePlaylistRepository)(nil).GetByID), ctx, id, userId)
}
