// Code generated by MockGen. DO NOT EDIT.
// Source: spotify_integration_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockSpotifyIntegrationRepository is a mock of SpotifyIntegrationRepository interface.
type MockSpotifyIntegrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyIntegrationRepositoryMockRecorder
}

// MockSpotifyIntegrationRepositoryMockRecorder is the mock recorder for MockSpotifyIntegrationRepository.
type MockSpotifyIntegrationRepositoryMockRecorder struct {
	mock *MockSpotifyIntegrationRepository
}

// NewMockSpotifyIntegrationRepository creates a new mock instance.
func NewMockSpotifyIntegrationRepository(ctrl *gomock.Controller) *MockSpotifyIntegrationRepository {
	mock := &MockSpotifyIntegrationRepository{ctrl: ctrl}
	mock.recorder = &MockSpotifyIntegrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyIntegrationRepository) EXPECT() *MockSpotifyIntegrationRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method.
func (m *MockSpotifyIntegrationRepository) CreateOrUpdate(ctx context.Context, userID string, integration *models.SpotifyIntegration) (*models.SpotifyIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, userID, integration)
	ret0, _ := ret[0].(*models.SpotifyIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockSpotifyIntegrationRepositoryMockRecorder) CreateOrUpdate(ctx, userID, integration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockSpotifyIntegrationRepository)(nil).CreateOrUpdate), ctx, userID, integration)
}

// Delete mocks base method.
func (m *MockSpotifyIntegrationRepository) Delete(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSpotifyIntegrationRepositoryMockRecorder) Delete(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSpotifyIntegrationRepository)(nil).Delete), ctx, userID)
}

// GetBySpotifyID mocks base method.
func (m *MockSpotifyIntegrationRepository) GetBySpotifyID(ctx context.Context, spotifyID string) (*models.SpotifyIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySpotifyID", ctx, spotifyID)
	ret0, _ := ret[0].(*models.SpotifyIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySpotifyID indicates an expected call of GetBySpotifyID.
func (mr *MockSpotifyIntegrationRepositoryMockRecorder) GetBySpotifyID(ctx, spotifyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySpotifyID", reflect.TypeOf((*MockSpotifyIntegrationRepository)(nil).GetBySpotifyID), ctx, spotifyID)
}

// GetByUserID mocks base method.
func (m *MockSpotifyIntegrationRepository) GetByUserID(ctx context.Context, userID string) (*models.SpotifyIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.SpotifyIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSpotifyIntegrationRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSpotifyIntegrationRepository)(nil).GetByUserID), ctx, userID)
}

// UpdateTokens mocks base method.
func (m *MockSpotifyIntegrationRepository) UpdateTokens(ctx context.Context, integrationID string, tokens *models.SpotifyIntegrationTokenRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokens", ctx, integrationID, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokens indicates an expected call of UpdateTokens.
func (mr *MockSpotifyIntegrationRepositoryMockRecorder) UpdateTokens(ctx, integrationID, tokens interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokens", reflect.TypeOf((*MockSpotifyIntegrationRepository)(nil).UpdateTokens), ctx, integrationID, tokens)
}
