// Code generated by MockGen. DO NOT EDIT.
// Source: sync_event_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockSyncEventRepository is a mock of SyncEventRepository interface.
type MockSyncEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSyncEventRepositoryMockRecorder
}

// MockSyncEventRepositoryMockRecorder is the mock recorder for MockSyncEventRepository.
type MockSyncEventRepositoryMockRecorder struct {
	mock *MockSyncEventRepository
}

// NewMockSyncEventRepository creates a new mock instance.
func NewMockSyncEventRepository(ctrl *gomock.Controller) *MockSyncEventRepository {
	mock := &MockSyncEventRepository{ctrl: ctrl}
	mock.recorder = &MockSyncEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncEventRepository) EXPECT() *MockSyncEventRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSyncEventRepository) Create(ctx context.Context, syncEvent *models.SyncEvent) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, syncEvent)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSyncEventRepositoryMockRecorder) Create(ctx, syncEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSyncEventRepository)(nil).Create), ctx, syncEvent)
}

// GetByBasePlaylistID mocks base method.
func (m *MockSyncEventRepository) GetByBasePlaylistID(ctx context.Context, basePlaylistID string) ([]*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBasePlaylistID", ctx, basePlaylistID)
	ret0, _ := ret[0].([]*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBasePlaylistID indicates an expected call of GetByBasePlaylistID.
func (mr *MockSyncEventRepositoryMockRecorder) GetByBasePlaylistID(ctx, basePlaylistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBasePlaylistID", reflect.TypeOf((*MockSyncEventRepository)(nil).GetByBasePlaylistID), ctx, basePlaylistID)
}

// GetByID mocks base method.
func (m *MockSyncEventRepository) GetByID(ctx context.Context, id string) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSyncEventRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSyncEventRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockSyncEventRepository) GetByUserID(ctx context.Context, userID string) ([]*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSyncEventRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSyncEventRepository)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockSyncEventRepository) Update(ctx context.Context, id string, syncEvent *models.SyncEvent) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, syncEvent)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSyncEventRepositoryMockRecorder) Update(ctx, id, syncEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSyncEventRepository)(nil).Update), ctx, id, syncEvent)
}
