// Code generated by MockGen. DO NOT EDIT.
// Source: child_playlist_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockChildPlaylistRepository is a mock of ChildPlaylistRepository interface.
type MockChildPlaylistRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChildPlaylistRepositoryMockRecorder
}

// MockChildPlaylistRepositoryMockRecorder is the mock recorder for MockChildPlaylistRepository.
type MockChildPlaylistRepositoryMockRecorder struct {
	mock *MockChildPlaylistRepository
}

// NewMockChildPlaylistRepository creates a new mock instance.
func NewMockChildPlaylistRepository(ctrl *gomock.Controller) *MockChildPlaylistRepository {
	mock := &MockChildPlaylistRepository{ctrl: ctrl}
	mock.recorder = &MockChildPlaylistRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChildPlaylistRepository) EXPECT() *MockChildPlaylistRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChildPlaylistRepository) Create(ctx context.Context, userID, basePlaylistID, name, description, spotifyPlaylistID string, filterRules *models.AudioFeatureFilters) (*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, basePlaylistID, name, description, spotifyPlaylistID, filterRules)
	ret0, _ := ret[0].(*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockChildPlaylistRepositoryMockRecorder) Create(ctx, userID, basePlaylistID, name, description, spotifyPlaylistID, filterRules interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChildPlaylistRepository)(nil).Create), ctx, userID, basePlaylistID, name, description, spotifyPlaylistID, filterRules)
}

// Delete mocks base method.
func (m *MockChildPlaylistRepository) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChildPlaylistRepositoryMockRecorder) Delete(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChildPlaylistRepository)(nil).Delete), ctx, id, userID)
}

// GetByBasePlaylistID mocks base method.
func (m *MockChildPlaylistRepository) GetByBasePlaylistID(ctx context.Context, basePlaylistID, userID string) ([]*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBasePlaylistID", ctx, basePlaylistID, userID)
	ret0, _ := ret[0].([]*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBasePlaylistID indicates an expected call of GetByBasePlaylistID.
func (mr *MockChildPlaylistRepositoryMockRecorder) GetByBasePlaylistID(ctx, basePlaylistID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBasePlaylistID", reflect.TypeOf((*MockChildPlaylistRepository)(nil).GetByBasePlaylistID), ctx, basePlaylistID, userID)
}

// GetByID mocks base method.
func (m *MockChildPlaylistRepository) GetByID(ctx context.Context, id, userID string) (*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockChildPlaylistRepositoryMockRecorder) GetByID(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockChildPlaylistRepository)(nil).GetByID), ctx, id, userID)
}

// Update mocks base method.
func (m *MockChildPlaylistRepository) Update(ctx context.Context, id, userID string, req *models.UpdateChildPlaylistRequest) (*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, req)
	ret0, _ := ret[0].(*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockChildPlaylistRepositoryMockRecorder) Update(ctx, id, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChildPlaylistRepository)(nil).Update), ctx, id, userID, req)
}
