// Code generated by MockGen. DO NOT EDIT.
// Source: sync_orchestrator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockSyncOrchestrator is a mock of SyncOrchestrator interface.
type MockSyncOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockSyncOrchestratorMockRecorder
}

// MockSyncOrchestratorMockRecorder is the mock recorder for MockSyncOrchestrator.
type MockSyncOrchestratorMockRecorder struct {
	mock *MockSyncOrchestrator
}

// NewMockSyncOrchestrator creates a new mock instance.
func NewMockSyncOrchestrator(ctrl *gomock.Controller) *MockSyncOrchestrator {
	mock := &MockSyncOrchestrator{ctrl: ctrl}
	mock.recorder = &MockSyncOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncOrchestrator) EXPECT() *MockSyncOrchestratorMockRecorder {
	return m.recorder
}

// SyncBasePlaylist mocks base method.
func (m *MockSyncOrchestrator) SyncBasePlaylist(ctx context.Context, userID, basePlaylistID string) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncBasePlaylist", ctx, userID, basePlaylistID)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncBasePlaylist indicates an expected call of SyncBasePlaylist.
func (mr *MockSyncOrchestratorMockRecorder) SyncBasePlaylist(ctx, userID, basePlaylistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncBasePlaylist", reflect.TypeOf((*MockSyncOrchestrator)(nil).SyncBasePlaylist), ctx, userID, basePlaylistID)
}
