// Code generated by MockGen. DO NOT EDIT.
// Source: sync_event_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockSyncEventServicer is a mock of SyncEventServicer interface.
type MockSyncEventServicer struct {
	ctrl     *gomock.Controller
	recorder *MockSyncEventServicerMockRecorder
}

// MockSyncEventServicerMockRecorder is the mock recorder for MockSyncEventServicer.
type MockSyncEventServicerMockRecorder struct {
	mock *MockSyncEventServicer
}

// NewMockSyncEventServicer creates a new mock instance.
func NewMockSyncEventServicer(ctrl *gomock.Controller) *MockSyncEventServicer {
	mock := &MockSyncEventServicer{ctrl: ctrl}
	mock.recorder = &MockSyncEventServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncEventServicer) EXPECT() *MockSyncEventServicerMockRecorder {
	return m.recorder
}

// CreateSyncEvent mocks base method.
func (m *MockSyncEventServicer) CreateSyncEvent(ctx context.Context, syncEvent *models.SyncEvent) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncEvent", ctx, syncEvent)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSyncEvent indicates an expected call of CreateSyncEvent.
func (mr *MockSyncEventServicerMockRecorder) CreateSyncEvent(ctx, syncEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncEvent", reflect.TypeOf((*MockSyncEventServicer)(nil).CreateSyncEvent), ctx, syncEvent)
}

// GetSyncEvent mocks base method.
func (m *MockSyncEventServicer) GetSyncEvent(ctx context.Context, id string) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncEvent", ctx, id)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncEvent indicates an expected call of GetSyncEvent.
func (mr *MockSyncEventServicerMockRecorder) GetSyncEvent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncEvent", reflect.TypeOf((*MockSyncEventServicer)(nil).GetSyncEvent), ctx, id)
}

// HasActiveSyncForBasePlaylist mocks base method.
func (m *MockSyncEventServicer) HasActiveSyncForBasePlaylist(ctx context.Context, userID, basePlaylistID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveSyncForBasePlaylist", ctx, userID, basePlaylistID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveSyncForBasePlaylist indicates an expected call of HasActiveSyncForBasePlaylist.
func (mr *MockSyncEventServicerMockRecorder) HasActiveSyncForBasePlaylist(ctx, userID, basePlaylistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveSyncForBasePlaylist", reflect.TypeOf((*MockSyncEventServicer)(nil).HasActiveSyncForBasePlaylist), ctx, userID, basePlaylistID)
}

// HasActiveSyncForUser mocks base method.
func (m *MockSyncEventServicer) HasActiveSyncForUser(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveSyncForUser", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveSyncForUser indicates an expected call of HasActiveSyncForUser.
func (mr *MockSyncEventServicerMockRecorder) HasActiveSyncForUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveSyncForUser", reflect.TypeOf((*MockSyncEventServicer)(nil).HasActiveSyncForUser), ctx, userID)
}

// UpdateSyncEvent mocks base method.
func (m *MockSyncEventServicer) UpdateSyncEvent(ctx context.Context, id string, syncEvent *models.SyncEvent) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncEvent", ctx, id, syncEvent)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSyncEvent indicates an expected call of UpdateSyncEvent.
func (mr *MockSyncEventServicerMockRecorder) UpdateSyncEvent(ctx, id, syncEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncEvent", reflect.TypeOf((*MockSyncEventServicer)(nil).UpdateSyncEvent), ctx, id, syncEvent)
}
