// Code generated by MockGen. DO NOT EDIT.
// Source: track_router_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockTrackRouterServicer is a mock of TrackRouterServicer interface.
type MockTrackRouterServicer struct {
	ctrl     *gomock.Controller
	recorder *MockTrackRouterServicerMockRecorder
}

// MockTrackRouterServicerMockRecorder is the mock recorder for MockTrackRouterServicer.
type MockTrackRouterServicerMockRecorder struct {
	mock *MockTrackRouterServicer
}

// NewMockTrackRouterServicer creates a new mock instance.
func NewMockTrackRouterServicer(ctrl *gomock.Controller) *MockTrackRouterServicer {
	mock := &MockTrackRouterServicer{ctrl: ctrl}
	mock.recorder = &MockTrackRouterServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackRouterServicer) EXPECT() *MockTrackRouterServicerMockRecorder {
	return m.recorder
}

// RouteTracksForBasePlaylist mocks base method.
func (m *MockTrackRouterServicer) RouteTracksForBasePlaylist(ctx context.Context, userID, basePlaylistID string) (*models.SyncEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteTracksForBasePlaylist", ctx, userID, basePlaylistID)
	ret0, _ := ret[0].(*models.SyncEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RouteTracksForBasePlaylist indicates an expected call of RouteTracksForBasePlaylist.
func (mr *MockTrackRouterServicerMockRecorder) RouteTracksForBasePlaylist(ctx, userID, basePlaylistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteTracksForBasePlaylist", reflect.TypeOf((*MockTrackRouterServicer)(nil).RouteTracksForBasePlaylist), ctx, userID, basePlaylistID)
}
