// Code generated by MockGen. DO NOT EDIT.
// Source: track_aggregator_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockTrackAggregatorServicer is a mock of TrackAggregatorServicer interface.
type MockTrackAggregatorServicer struct {
	ctrl     *gomock.Controller
	recorder *MockTrackAggregatorServicerMockRecorder
}

// MockTrackAggregatorServicerMockRecorder is the mock recorder for MockTrackAggregatorServicer.
type MockTrackAggregatorServicerMockRecorder struct {
	mock *MockTrackAggregatorServicer
}

// NewMockTrackAggregatorServicer creates a new mock instance.
func NewMockTrackAggregatorServicer(ctrl *gomock.Controller) *MockTrackAggregatorServicer {
	mock := &MockTrackAggregatorServicer{ctrl: ctrl}
	mock.recorder = &MockTrackAggregatorServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackAggregatorServicer) EXPECT() *MockTrackAggregatorServicerMockRecorder {
	return m.recorder
}

// AggregatePlaylistData mocks base method.
func (m *MockTrackAggregatorServicer) AggregatePlaylistData(ctx context.Context, basePlaylistID string) (*models.PlaylistTracksInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregatePlaylistData", ctx, basePlaylistID)
	ret0, _ := ret[0].(*models.PlaylistTracksInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregatePlaylistData indicates an expected call of AggregatePlaylistData.
func (mr *MockTrackAggregatorServicerMockRecorder) AggregatePlaylistData(ctx, basePlaylistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregatePlaylistData", reflect.TypeOf((*MockTrackAggregatorServicer)(nil).AggregatePlaylistData), ctx, basePlaylistID)
}
