// Code generated by MockGen. DO NOT EDIT.
// Source: spotify_api_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockSpotifyAPIServicer is a mock of SpotifyAPIServicer interface.
type MockSpotifyAPIServicer struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyAPIServicerMockRecorder
}

// MockSpotifyAPIServicerMockRecorder is the mock recorder for MockSpotifyAPIServicer.
type MockSpotifyAPIServicerMockRecorder struct {
	mock *MockSpotifyAPIServicer
}

// NewMockSpotifyAPIServicer creates a new mock instance.
func NewMockSpotifyAPIServicer(ctrl *gomock.Controller) *MockSpotifyAPIServicer {
	mock := &MockSpotifyAPIServicer{ctrl: ctrl}
	mock.recorder = &MockSpotifyAPIServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyAPIServicer) EXPECT() *MockSpotifyAPIServicerMockRecorder {
	return m.recorder
}

// GetUserPlaylists mocks base method.
func (m *MockSpotifyAPIServicer) GetUserPlaylists(ctx context.Context, userID string) ([]*models.SpotifyPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPlaylists", ctx, userID)
	ret0, _ := ret[0].([]*models.SpotifyPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPlaylists indicates an expected call of GetUserPlaylists.
func (mr *MockSpotifyAPIServicerMockRecorder) GetUserPlaylists(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPlaylists", reflect.TypeOf((*MockSpotifyAPIServicer)(nil).GetUserPlaylists), ctx, userID)
}
