// Code generated by MockGen. DO NOT EDIT.
// Source: auth_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	services "github.com/ngomez18/playlist-router/internal/services"
)

// MockAuthServicer is a mock of AuthServicer interface.
type MockAuthServicer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServicerMockRecorder
}

// MockAuthServicerMockRecorder is the mock recorder for MockAuthServicer.
type MockAuthServicerMockRecorder struct {
	mock *MockAuthServicer
}

// NewMockAuthServicer creates a new mock instance.
func NewMockAuthServicer(ctrl *gomock.Controller) *MockAuthServicer {
	mock := &MockAuthServicer{ctrl: ctrl}
	mock.recorder = &MockAuthServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServicer) EXPECT() *MockAuthServicerMockRecorder {
	return m.recorder
}

// GenerateSpotifyAuthURL mocks base method.
func (m *MockAuthServicer) GenerateSpotifyAuthURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSpotifyAuthURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSpotifyAuthURL indicates an expected call of GenerateSpotifyAuthURL.
func (mr *MockAuthServicerMockRecorder) GenerateSpotifyAuthURL(state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSpotifyAuthURL", reflect.TypeOf((*MockAuthServicer)(nil).GenerateSpotifyAuthURL), state)
}

// HandleSpotifyCallback mocks base method.
func (m *MockAuthServicer) HandleSpotifyCallback(ctx context.Context, code, state string) (*services.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSpotifyCallback", ctx, code, state)
	ret0, _ := ret[0].(*services.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleSpotifyCallback indicates an expected call of HandleSpotifyCallback.
func (mr *MockAuthServicerMockRecorder) HandleSpotifyCallback(ctx, code, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSpotifyCallback", reflect.TypeOf((*MockAuthServicer)(nil).HandleSpotifyCallback), ctx, code, state)
}
