// Code generated by MockGen. DO NOT EDIT.
// Source: track_router_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockTrackRouterServicer is a mock of TrackRouterServicer interface.
type MockTrackRouterServicer struct {
	ctrl     *gomock.Controller
	recorder *MockTrackRouterServicerMockRecorder
}

// MockTrackRouterServicerMockRecorder is the mock recorder for MockTrackRouterServicer.
type MockTrackRouterServicerMockRecorder struct {
	mock *MockTrackRouterServicer
}

// NewMockTrackRouterServicer creates a new mock instance.
func NewMockTrackRouterServicer(ctrl *gomock.Controller) *MockTrackRouterServicer {
	mock := &MockTrackRouterServicer{ctrl: ctrl}
	mock.recorder = &MockTrackRouterServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrackRouterServicer) EXPECT() *MockTrackRouterServicerMockRecorder {
	return m.recorder
}

// RouteTracksToChildren mocks base method.
func (m *MockTrackRouterServicer) RouteTracksToChildren(ctx context.Context, tracks *models.PlaylistTracksInfo, childPlaylists []*models.ChildPlaylist) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteTracksToChildren", ctx, tracks, childPlaylists)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RouteTracksToChildren indicates an expected call of RouteTracksToChildren.
func (mr *MockTrackRouterServicerMockRecorder) RouteTracksToChildren(ctx, tracks, childPlaylists interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteTracksToChildren", reflect.TypeOf((*MockTrackRouterServicer)(nil).RouteTracksToChildren), ctx, tracks, childPlaylists)
}
