// Code generated by MockGen. DO NOT EDIT.
// Source: spotify_integration_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockSpotifyIntegrationServicer is a mock of SpotifyIntegrationServicer interface.
type MockSpotifyIntegrationServicer struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyIntegrationServicerMockRecorder
}

// MockSpotifyIntegrationServicerMockRecorder is the mock recorder for MockSpotifyIntegrationServicer.
type MockSpotifyIntegrationServicerMockRecorder struct {
	mock *MockSpotifyIntegrationServicer
}

// NewMockSpotifyIntegrationServicer creates a new mock instance.
func NewMockSpotifyIntegrationServicer(ctrl *gomock.Controller) *MockSpotifyIntegrationServicer {
	mock := &MockSpotifyIntegrationServicer{ctrl: ctrl}
	mock.recorder = &MockSpotifyIntegrationServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyIntegrationServicer) EXPECT() *MockSpotifyIntegrationServicerMockRecorder {
	return m.recorder
}

// CreateOrUpdateIntegration mocks base method.
func (m *MockSpotifyIntegrationServicer) CreateOrUpdateIntegration(ctx context.Context, userID string, integration *models.SpotifyIntegration) (*models.SpotifyIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateIntegration", ctx, userID, integration)
	ret0, _ := ret[0].(*models.SpotifyIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateIntegration indicates an expected call of CreateOrUpdateIntegration.
func (mr *MockSpotifyIntegrationServicerMockRecorder) CreateOrUpdateIntegration(ctx, userID, integration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateIntegration", reflect.TypeOf((*MockSpotifyIntegrationServicer)(nil).CreateOrUpdateIntegration), ctx, userID, integration)
}

// DeleteIntegration mocks base method.
func (m *MockSpotifyIntegrationServicer) DeleteIntegration(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIntegration", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIntegration indicates an expected call of DeleteIntegration.
func (mr *MockSpotifyIntegrationServicerMockRecorder) DeleteIntegration(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIntegration", reflect.TypeOf((*MockSpotifyIntegrationServicer)(nil).DeleteIntegration), ctx, userID)
}

// GetIntegrationBySpotifyID mocks base method.
func (m *MockSpotifyIntegrationServicer) GetIntegrationBySpotifyID(ctx context.Context, spotifyID string) (*models.SpotifyIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntegrationBySpotifyID", ctx, spotifyID)
	ret0, _ := ret[0].(*models.SpotifyIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntegrationBySpotifyID indicates an expected call of GetIntegrationBySpotifyID.
func (mr *MockSpotifyIntegrationServicerMockRecorder) GetIntegrationBySpotifyID(ctx, spotifyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntegrationBySpotifyID", reflect.TypeOf((*MockSpotifyIntegrationServicer)(nil).GetIntegrationBySpotifyID), ctx, spotifyID)
}

// GetIntegrationByUserID mocks base method.
func (m *MockSpotifyIntegrationServicer) GetIntegrationByUserID(ctx context.Context, userID string) (*models.SpotifyIntegration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIntegrationByUserID", ctx, userID)
	ret0, _ := ret[0].(*models.SpotifyIntegration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIntegrationByUserID indicates an expected call of GetIntegrationByUserID.
func (mr *MockSpotifyIntegrationServicerMockRecorder) GetIntegrationByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIntegrationByUserID", reflect.TypeOf((*MockSpotifyIntegrationServicer)(nil).GetIntegrationByUserID), ctx, userID)
}

// UpdateTokens mocks base method.
func (m *MockSpotifyIntegrationServicer) UpdateTokens(ctx context.Context, integrationID string, tokens *models.SpotifyIntegrationTokenRefresh) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTokens", ctx, integrationID, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTokens indicates an expected call of UpdateTokens.
func (mr *MockSpotifyIntegrationServicerMockRecorder) UpdateTokens(ctx, integrationID, tokens interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTokens", reflect.TypeOf((*MockSpotifyIntegrationServicer)(nil).UpdateTokens), ctx, integrationID, tokens)
}
