// Code generated by MockGen. DO NOT EDIT.
// Source: child_playlist_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockChildPlaylistServicer is a mock of ChildPlaylistServicer interface.
type MockChildPlaylistServicer struct {
	ctrl     *gomock.Controller
	recorder *MockChildPlaylistServicerMockRecorder
}

// MockChildPlaylistServicerMockRecorder is the mock recorder for MockChildPlaylistServicer.
type MockChildPlaylistServicerMockRecorder struct {
	mock *MockChildPlaylistServicer
}

// NewMockChildPlaylistServicer creates a new mock instance.
func NewMockChildPlaylistServicer(ctrl *gomock.Controller) *MockChildPlaylistServicer {
	mock := &MockChildPlaylistServicer{ctrl: ctrl}
	mock.recorder = &MockChildPlaylistServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChildPlaylistServicer) EXPECT() *MockChildPlaylistServicerMockRecorder {
	return m.recorder
}

// CreateChildPlaylist mocks base method.
func (m *MockChildPlaylistServicer) CreateChildPlaylist(ctx context.Context, userID, basePlaylistID string, input *models.CreateChildPlaylistRequest) (*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChildPlaylist", ctx, userID, basePlaylistID, input)
	ret0, _ := ret[0].(*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChildPlaylist indicates an expected call of CreateChildPlaylist.
func (mr *MockChildPlaylistServicerMockRecorder) CreateChildPlaylist(ctx, userID, basePlaylistID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChildPlaylist", reflect.TypeOf((*MockChildPlaylistServicer)(nil).CreateChildPlaylist), ctx, userID, basePlaylistID, input)
}

// DeleteChildPlaylist mocks base method.
func (m *MockChildPlaylistServicer) DeleteChildPlaylist(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChildPlaylist", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChildPlaylist indicates an expected call of DeleteChildPlaylist.
func (mr *MockChildPlaylistServicerMockRecorder) DeleteChildPlaylist(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChildPlaylist", reflect.TypeOf((*MockChildPlaylistServicer)(nil).DeleteChildPlaylist), ctx, id, userID)
}

// GetChildPlaylist mocks base method.
func (m *MockChildPlaylistServicer) GetChildPlaylist(ctx context.Context, id, userID string) (*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildPlaylist", ctx, id, userID)
	ret0, _ := ret[0].(*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildPlaylist indicates an expected call of GetChildPlaylist.
func (mr *MockChildPlaylistServicerMockRecorder) GetChildPlaylist(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildPlaylist", reflect.TypeOf((*MockChildPlaylistServicer)(nil).GetChildPlaylist), ctx, id, userID)
}

// GetChildPlaylistsByBasePlaylistID mocks base method.
func (m *MockChildPlaylistServicer) GetChildPlaylistsByBasePlaylistID(ctx context.Context, basePlaylistID, userID string) ([]*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildPlaylistsByBasePlaylistID", ctx, basePlaylistID, userID)
	ret0, _ := ret[0].([]*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildPlaylistsByBasePlaylistID indicates an expected call of GetChildPlaylistsByBasePlaylistID.
func (mr *MockChildPlaylistServicerMockRecorder) GetChildPlaylistsByBasePlaylistID(ctx, basePlaylistID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildPlaylistsByBasePlaylistID", reflect.TypeOf((*MockChildPlaylistServicer)(nil).GetChildPlaylistsByBasePlaylistID), ctx, basePlaylistID, userID)
}

// UpdateChildPlaylist mocks base method.
func (m *MockChildPlaylistServicer) UpdateChildPlaylist(ctx context.Context, id, userID string, input *models.UpdateChildPlaylistRequest) (*models.ChildPlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChildPlaylist", ctx, id, userID, input)
	ret0, _ := ret[0].(*models.ChildPlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChildPlaylist indicates an expected call of UpdateChildPlaylist.
func (mr *MockChildPlaylistServicerMockRecorder) UpdateChildPlaylist(ctx, id, userID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChildPlaylist", reflect.TypeOf((*MockChildPlaylistServicer)(nil).UpdateChildPlaylist), ctx, id, userID, input)
}
