// Code generated by MockGen. DO NOT EDIT.
// Source: base_playlist_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ngomez18/playlist-router/internal/models"
)

// MockBasePlaylistServicer is a mock of BasePlaylistServicer interface.
type MockBasePlaylistServicer struct {
	ctrl     *gomock.Controller
	recorder *MockBasePlaylistServicerMockRecorder
}

// MockBasePlaylistServicerMockRecorder is the mock recorder for MockBasePlaylistServicer.
type MockBasePlaylistServicerMockRecorder struct {
	mock *MockBasePlaylistServicer
}

// NewMockBasePlaylistServicer creates a new mock instance.
func NewMockBasePlaylistServicer(ctrl *gomock.Controller) *MockBasePlaylistServicer {
	mock := &MockBasePlaylistServicer{ctrl: ctrl}
	mock.recorder = &MockBasePlaylistServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasePlaylistServicer) EXPECT() *MockBasePlaylistServicerMockRecorder {
	return m.recorder
}

// CreateBasePlaylist mocks base method.
func (m *MockBasePlaylistServicer) CreateBasePlaylist(ctx context.Context, input *models.CreateBasePlaylistRequest) (*models.BasePlaylist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBasePlaylist", ctx, input)
	ret0, _ := ret[0].(*models.BasePlaylist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBasePlaylist indicates an expected call of CreateBasePlaylist.
func (mr *MockBasePlaylistServicerMockRecorder) CreateBasePlaylist(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBasePlaylist", reflect.TypeOf((*MockBasePlaylistServicer)(nil).CreateBasePlaylist), ctx, input)
}
